---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/tags: rpm-build
  name: get-rpm-sources
spec:
  description: |-
    Download source files referenced by a spec file.
  params:
    - description: Package name to clone
      name: package-name
      type: string
  steps:
    - name: download
      image: "quay.io/redhat-user-workloads/rhel-on-konflux-tenant/\
              tooling/get-rpm-sources-container:\
              7551f7bcb4e2bd22c2042c51fb327a3c06e407bd"
      script: |
        set -x
        cd "$(workspaces.sources.path)/source"
        copr-distgit-client --forked-from https://src.fedoraproject.org/git/rpms/$(params.package-name) sources
  workspaces:
    - name: sources
